name: Test

on: 
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3

      - name: Setup Go 1.20.2
        uses: actions/setup-go@v4
        with:
          go-version: '1.20.2'
      
      - name: Install dependencies
        run: |
          go get .
          go mod tidy
      
      - name: Test
        run: go test -v ./...